name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Extract version from Dockerfile LABEL
        id: extract_version
        run: |
          VERSION=$(grep -oP 'LABEL\s+version="\K[^"]+' Dockerfile)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/ansible-docker-rocky9:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ansible-docker-rocky9:${{ env.VERSION }}
